
repos:
  # Sort python imports
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    - id: reorder-python-imports
    
  # Format the code with a conventional PEP8 style
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
